### ISSUE TITLE
HTTP Internal Server

### ISSUE THREAD

**Issue by ghost** [bubbledevteam/bubble-client-swift#1]
I do not know if this is the right place but with Diabox V2020.06.05_4.0, I use the internal HTTP Server.
I'm working on the developpment of my personnal app to "track" my diabet but in the same time I learn Android development with Kotlin.

I have a problem with the internal HTTP Server, I suspect that Android 10 kill regularely this server.

**Comment by bubbledevteam** [comment]
Sorry, here is iOS.

For android HTTP server ,you can follow how xdrip+ does
